[package]
name = "sqloxide"
version = "0.1.12"
authors = ["Will Eaton <me@wseaton.com>"]
edition = "2018"

[lib]
name = "sqloxide"
crate-type = ["cdylib"]

[dependencies]
pythonize = "0.15.0"

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module"]

[dependencies.sqlparser]
version = "0.13.0"
features = ["json_example"]
