[package]
name = "sqloxide"
version = "0.1.11"
authors = ["Will Eaton <me@wseaton.com>"]
edition = "2018"

[lib]
name = "sqloxide"
crate-type = ["cdylib"]

[dependencies]
pythonize = "0.12.1"

[dependencies.pyo3]
version = "0.14.1"
features = ["extension-module"]

[dependencies.sqlparser]
version = "0.9.0"
features = ["json_example"]
